#!/usr/bin/python

import numpy
import math
                
G = 6.67*10**(-11)
M = 5.97*10**24
R = 6371*10**3

"""print("Choose among the options for time (seconds) input: ")"""
T = float (input("Time of choice: "))
"""b)"""
h = ((G*M*T**2) / 4*(math.pi)**2)**1/3 - R  
print (h, "meters \n")

"""c) once a day; 24 hours = 86,400 sec"""
Ttwenty = float(input("Input 86400 sec: "))
htwenty = ((G*M*Ttwenty**2) / 4*(math.pi)**2)**1/3 - R  
print (htwenty, "meters \n")

"""c) once every 90 minutes = 5400 sec"""
Tninety = float (input("Input 5400 sec"))
hninety = ((G*M*Tninety**2) / 4*(math.pi)**2)**1/3 - R  
print (hninety, "meters \n")

"""c) once every 45 minutes = 2700 sec"""
Tforty = float (input("Input 2700 sec"))
hforty = ((G*M*Tforty**2) / 4*(math.pi)**2)**1/3 - R  
print (hforty, "meters \n")
print("Satellites move faster when closer to Earth's surface. \n")

"""d) 23.93 hours = 86148 sec"""
Tthree = float (input("Input 86148 sec"))
hthree = ((G*M*Tthree**2) / 4*(math.pi)**2)**1/3 - R  
print (hthree, "meters \n")
print("A geosynchronous satellite is a satellite that is in synchrony with the Earth's orbit. Its orbital period is the same as the Earth's rotation period. The length of the day of 1 Earth day is 23.93 hours")"
print("The difference in the altitude is ", htwenty - hthree, "meters.")
